### ISSUE TITLE
Parallel computing in `kissplice2counts` function

### ISSUE THREAD

**Issue by sylvainschmitt** [aursiber/kissDE#1]
Dear kissDE dev-team,

First thank you for your great work.

I am currently using your package with pretty heavy variant files on a HPC. Consequently I thought it could be great to use a bit of parallel computing to increase computation speed. I just looked a bit into `kissplice2counts` function, and it seems to me that the for loop at line 165 could be parallelized:
https://github.com/aursiber/kissDE/blob/d4b4277474dda27ee59872657cf8bfca18ef6e6b/R/kissplice2counts.R#L165
If I am right you could have written it with a `apply`-family function because the read of one line does not depend on the previous line ? And if we can write it with a `apply`-family function, we can also write it with a `apply`-family function from package parallel and thus decrease computation time.

So if you think I am right, and it could be interesting, I don't bother to help.

Best,

Sylvain

**Comment by aursiber** [comment]
Hi Sylvain,
First of all, thank you for your interest in `kissDE`.

We are currently working on widely optimize the package and reduce some bottlenecks. 
More precisely we are working on the vectorization of some loops. 
Your suggestion to parallelize is a very interesting track and we will think about it in the near future.

Best,
Aurélie.

**Comment by sylvainschmitt** [comment]
Ok great, I'll follow the development with attention to improve my computing time.

If you think I can dive into the code to help parallelize some bottleneck, I would be happy to help (besides it is always easier for the developer(s) that have a better idea of the code architecture).

Best,
Sylvain

**Comment by aursiber** [comment]
Hi Sylvain,
`kissDE` has been available on Bioconductor since April and a lot of improvements have been made since on the development version available on GitHub. Some codes have been cleaned and simplified, others optimized. The calculation times have been really reduced.
So you can test the GitHub version of `kissDE` on your data and tell us if these changes are beneficial to you.
Best,
Aurélie.
